# Generated by Django 2.2.6 on 2019-11-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='feito',
            field=models.BooleanField(default=False),
        ),
    ]
