# Generated by Django 2.2.6 on 2019-11-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_feito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='feito',
        ),
    ]
