# Generated by Django 2.2.6 on 2019-11-09 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_todo_feito'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 5, 25, 26, 60488, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
