# Generated by Django 2.2.6 on 2019-11-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191109_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_date',
            field=models.DateTimeField(null=True),
        ),
    ]
